{
   "native_images":{
      "native:8.1":{
         "supported_docker_images":[
            "python3",
            "python3-deb",
            "python3-ubi",
            "py3-tools",
            "py3-tools-ubi",
            "crypto",
            "readpdf",
            "parse-emails",
            "docxpy",
            "sklearn",
            "pandas",
            "ippysocks-py3",
            "oauthlib",
            "unzip",
            "py3ews",
            "taxii2",
            "pan-os-python",
            "slackv3",
            "google-api-py3",
            "boto3py3",
            "pyjwt3",
            "joe-security",
            "slack",
            "office-utils",
            "chromium",
            "tesseract"
         ],
         "docker_ref": "demisto/py3-native:8.1.0.40949"
      },
      "native:dev":{
         "supported_docker_images":[
            "python3",
            "python3-deb",
            "python3-ubi",
            "py3-tools",
            "py3-tools-ubi",
            "crypto",
            "readpdf",
            "parse-emails",
            "docxpy",
            "sklearn",
            "pandas",
            "ippysocks-py3",
            "oauthlib",
            "unzip",
            "py3ews",
            "taxii2",
            "pan-os-python",
            "slackv3",
            "google-api-py3",
            "boto3py3",
            "pyjwt3",
            "joe-security",
            "slack",
            "office-utils",
            "chromium",
            "tesseract"
         ]
      }
   },
   "ignored_content_items":[
      {
         "id":"UnzipFile",
         "reason":"Failed unit-test: test_unrar_no_password",
         "ignored_native_images":[
            "native:8.1"
         ]
      },
      {
         "id":"DockerHardeningCheck",
         "reason":"Failed unit-test: get_default_gateway (ip command does not exist).",
         "ignored_native_images":[
            "native:8.1"
         ]
      },
      {
         "id":"FetchIndicatorsFromFile",
         "reason":"ElementTree object (xml) in python3.9 has getiterator attribute while in python 3.10 this attribute does not exist - causing unit tests failures: test_xls_file_to_indicator_list_1, test_xls_file_to_indicator_list_2, test_xls_file_to_indicator_list_3, test_xls_file_to_indicator_list_4.",
         "ignored_native_images":[
            "native:8.1"
         ]
      },
      {
         "id":"Traps",
         "reason":"Integration is Deprecated.",
         "ignored_native_images":[
            "native:8.1"
         ]
      },
      {
         "id":"Rasterize",
         "reason":"Issue: CRTX-72338.",
         "ignored_native_images":[
            "native:8.1"
         ]
      }
   ],
   "flags_versions_mapping": {
      "native:dev" : "native:dev",
      "native:ga" : "native:8.1",
      "native:maintenance" : ""
   }
}